/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import javax.swing.JOptionPane;
import model.Tarefa;
import dao.DAOTarefa;
import java.awt.Component;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import util.ConvesorData;

/**
 *
 * @author Senac
 */
public class ViewTarefas extends javax.swing.JFrame {
    DAOTarefa dAOTarefa =  new DAOTarefa();
 Tarefa tarefa = new Tarefa ();
    ArrayList<Tarefa>lista = dAOTarefa.listarTarefaDAO();
    String cadAlt = "Cad";
 
 
    public ViewTarefas() {
        initComponents();
        setLocationRelativeTo(this);
       atualizarTarefa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTFtarefa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTFdescricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbtabela = new javax.swing.JTable();
        jBtAddTarefa = new javax.swing.JButton();
        jBtSair = new javax.swing.JButton();
        jbtLimpar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTfId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jDateCData = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBtPesquisarView = new javax.swing.JButton();
        jTFhorainicio = new javax.swing.JFormattedTextField();
        jTFHoraFim = new javax.swing.JFormattedTextField();
        jCBStatus = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                windowFechar(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRAR TAREFA");

        jTFtarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFtarefaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Tarefa:");

        jTFdescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFdescricaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Descrição");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TAREFA:");

        jTbtabela.setBackground(new java.awt.Color(204, 204, 204));
        jTbtabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tarefa", "Descrição", "Data:", "Inicio.H:", "Termi.H:", "Status:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbtabela);
        if (jTbtabela.getColumnModel().getColumnCount() > 0) {
            jTbtabela.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTbtabela.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTbtabela.getColumnModel().getColumn(4).setPreferredWidth(80);
            jTbtabela.getColumnModel().getColumn(5).setPreferredWidth(80);
            jTbtabela.getColumnModel().getColumn(6).setPreferredWidth(100);
        }

        jBtAddTarefa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-add-properties-24.png"))); // NOI18N
        jBtAddTarefa.setText("Adicionar");
        jBtAddTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionAdd(evt);
            }
        });

        jBtSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-exit-24.png"))); // NOI18N
        jBtSair.setText("Sair");
        jBtSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionSair(evt);
            }
        });

        jbtLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-clean-24.png"))); // NOI18N
        jbtLimpar.setText("Limpar");
        jbtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLimparActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-edit-24.png"))); // NOI18N
        jButton4.setText("Editar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionEditar(evt);
            }
        });

        jTfId.setEditable(false);
        jTfId.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-erase-24.png"))); // NOI18N
        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionExcluirTarefa(evt);
            }
        });

        jDateCData.setDateFormatString("d '/' MM '/' y");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Hora Inicio:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hora Final:");

        jBtPesquisarView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-search-in-cloud-24.png"))); // NOI18N
        jBtPesquisarView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actionPesquisarView(evt);
            }
        });

        try {
            jTFhorainicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTFHoraFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jCBStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "PENDENTE", "EM ANDAMENTO", "CONCLUÍDA" }));
        jCBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBStatusActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Status:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/4GZ9.gif"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtAddTarefa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBtSair)
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 371, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(154, 154, 154))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateCData, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jCBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel9)))
                                .addGap(110, 110, 110)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFhorainicio, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jTFHoraFim, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTFdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 817, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTFtarefa, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(99, 99, 99))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTfId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)
                                        .addComponent(jBtPesquisarView, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(472, 472, 472)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jBtSair))
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFtarefa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtPesquisarView, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addComponent(jTFdescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateCData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBStatus)
                            .addComponent(jTFhorainicio))
                        .addComponent(jTFHoraFim, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtAddTarefa)
                        .addComponent(jbtLimpar)
                        .addComponent(jButton4)
                        .addComponent(jButton1))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actionAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionAdd
        adicionatarefas();
        limparCampos();
    }//GEN-LAST:event_actionAdd

    private void jbtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLimparActionPerformed
       limparCampos();
    }//GEN-LAST:event_jbtLimparActionPerformed

    private void actionEditar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionEditar
        editarTarefa();
    }//GEN-LAST:event_actionEditar

    private void actionSair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionSair
      exit();
        
    }//GEN-LAST:event_actionSair

    private void actionExcluirTarefa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionExcluirTarefa
      
        excluirTarefa();
      
    }//GEN-LAST:event_actionExcluirTarefa

    private void actionPesquisarView(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPesquisarView
       PesquisarView();
    }//GEN-LAST:event_actionPesquisarView

    private void windowFechar(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowFechar
       UIManager.put("OptionPane.yesButtonText", "Sim");
      UIManager.put("OptionPane.noButtonText", "Não");
      
       int op = JOptionPane.showConfirmDialog(null, "Você desejar encerrar a sua sessão?", "Atenção", JOptionPane.YES_NO_OPTION);
       
        if (op == 0){
        
         this.dispose();
        }
    }//GEN-LAST:event_windowFechar

    private void jCBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBStatusActionPerformed

    private void jTFdescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFdescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFdescricaoActionPerformed

    private void jTFtarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFtarefaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFtarefaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTarefas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTarefas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtAddTarefa;
    private javax.swing.JButton jBtPesquisarView;
    private javax.swing.JButton jBtSair;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCBStatus;
    private com.toedter.calendar.JDateChooser jDateCData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jTFHoraFim;
    private javax.swing.JTextField jTFdescricao;
    private javax.swing.JFormattedTextField jTFhorainicio;
    private javax.swing.JTextField jTFtarefa;
    private javax.swing.JTable jTbtabela;
    private javax.swing.JTextField jTfId;
    private javax.swing.JButton jbtLimpar;
    // End of variables declaration//GEN-END:variables

    private void adicionatarefas() {  
        DateTimeFormatter formatadorHora = DateTimeFormatter.ofPattern("HH:mm");
        
        Date dataSelecionada = jDateCData.getDate();
        String horaInicioTexto = jTFhorainicio.getText();
        String horaFimTexto = jTFHoraFim.getText();
        
        LocalTime horaInicio;
        LocalTime horaFim;
        
        try {
        horaInicio = LocalTime.parse(horaInicioTexto, formatadorHora);
        horaFim = LocalTime.parse(horaFimTexto, formatadorHora);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this,"Hora inválida! use o formato HH:mm ", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (jTFtarefa.getText() == null || jTFtarefa.getText().trim().equals("")|| 
            jTFdescricao.getText() == null || jTFdescricao.getText().trim().equals("")||
            jDateCData.getDate() == null ||  jCBStatus.getSelectedItem() == "") {
            
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios!", "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
       
     
       // tarefa = new Tarefa();
        DAOTarefa dao = new DAOTarefa();
        Date dateSelecionado = jDateCData.getDate();
        
        tarefa.setTarefa(jTFtarefa.getText());
        tarefa.setDescricao(jTFdescricao.getText());
        tarefa.setDataTarefa(ConvesorData.converterDateParaLocalDate(dateSelecionado));
        tarefa.setHorainicio(LocalTime.parse(jTFhorainicio.getText()));
        tarefa.setHoraFim (LocalTime.parse(jTFHoraFim.getText()));
        tarefa.setStatus(String.valueOf(jCBStatus.getSelectedItem()));
        
        
        
       if (cadAlt.equals("Cad")) {
            if (dao.salvarTarefaDAO(tarefa) > 0) {
            JOptionPane.showMessageDialog(null, "Cadastro ok!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
            atualizarTarefa();
           
        } else {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar", "Erro", JOptionPane.ERROR_MESSAGE);
        }
           
        } else {
           
            tarefa.setId(Integer.parseInt(jTfId.getText()));
            if (dAOTarefa.editarTArefaDAO(tarefa)) {
                JOptionPane.showMessageDialog(null, "Tarefa Atualizada com Sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();
            atualizarTarefa();
             //cadAlt = "Cad";  
            } else {
                JOptionPane.showMessageDialog(null, "Erro ao Atualizar", "Erro", JOptionPane.ERROR_MESSAGE);
            }
           
        }
       
        
    }
  
    

    private void limparCampos() {
        jTfId.setText("");
        jDateCData.setDate(null);
        jTFtarefa.setText("");
        jTFdescricao.setText("");
        jTFhorainicio.setText("");
        jTFHoraFim.setText("");
        jCBStatus.setSelectedIndex(0);
    }

    private void atualizarTarefa() {
         DAOTarefa dao = new DAOTarefa();
        lista = dao.listarTarefaDAO();
        
        DefaultTableModel model = (DefaultTableModel) jTbtabela.getModel();
        model.setRowCount(0);
       
        for (Tarefa t : lista) {
            model.addRow(new Object[]{
                t.getId(),
                t.getTarefa(),
                t.getDescricao(),
                t.getDataTarefa(),
                t.getHorainicio(),
                t.getHoraFim(),
                t.getStatus()
              
            });
            
            aplicarFormantoDataBR(jTbtabela, 3);
           
        }
        
        
    }


    private void editarTarefa() {
        cadAlt = "Alt";
       
       int linha = jTbtabela.getSelectedRow();
        if (linha < 0) {
            JOptionPane.showMessageDialog(null, "Você deve selecionar um registro", "Erro", JOptionPane.ERROR_MESSAGE);
           
        } else {
            int id = (int) jTbtabela.getValueAt(linha, 0);
            String titulo = (String)jTbtabela.getValueAt(linha, 1);
            String descricao = (String)jTbtabela.getValueAt(linha, 2);
            LocalDate dtTarefa = (LocalDate) jTbtabela.getValueAt(linha, 3);
            LocalTime hInicio = (LocalTime) jTbtabela.getValueAt(linha, 4);
            LocalTime hFim = (LocalTime) jTbtabela.getValueAt (linha, 5);
            String status = (String)jTbtabela.getValueAt(linha, 6);
            
            
            tarefa = new Tarefa();
            tarefa.setId(id);
            tarefa.setTarefa(titulo);
            tarefa.setDescricao(descricao);
            tarefa.setDataTarefa(dtTarefa);
            tarefa.setHorainicio(hInicio);
            tarefa.setHoraFim(hFim);
            tarefa.setStatus(status);
           
            jTfId.setText(String.valueOf(id));
            jTFtarefa.setText(titulo);
            jTFdescricao.setText(descricao);
            jDateCData.setDate (ConvesorData.converterLocalDateParaDate(dtTarefa));
            jTFhorainicio.setText(String.valueOf(hInicio));
            jTFHoraFim.setText(String.valueOf(hFim));
            jCBStatus.setSelectedItem(status);
        }
       
    }

    private void excluirTarefa() {
     DAOTarefa dao = new DAOTarefa();
     int linha = jTbtabela.getSelectedRow();
      
        if (linha < 0 ) {
        JOptionPane.showMessageDialog(null, "Um registro deve ser selecionado.", "Error!.", JOptionPane.ERROR_MESSAGE);
            
        } else {
         int id = (int) jTbtabela.getValueAt(linha, 0);             
         
         if  (id != 0) {
             this.tarefa = new Tarefa();
             tarefa.setId(id);
             dao.excluirTarefaDAO(tarefa.getId());
              JOptionPane.showMessageDialog(null, "Cadastro excluido com sucesso.", "Cadastro.", JOptionPane.ERROR_MESSAGE);
              atualizarTarefa();
        } 
         else {
              JOptionPane.showMessageDialog(null, "Erro ao excluír registro.", "Error.", JOptionPane.ERROR_MESSAGE);
         }
                 
        }
    }
    
    private void aplicarFormantoDataBR(JTable tabela, int indiceColunaData){
        
        tabela.getColumnModel().getColumn(indiceColunaData).setCellRenderer(new DefaultTableCellRenderer(){
            private final DateTimeFormatter formatoBR = DateTimeFormatter.ofPattern("dd/MM/yyyy");
                    
    
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus,
    int row, int column){
         if (value instanceof LocalDate) {
             value = ((LocalDate)value).format(formatoBR);
                
            }
        return super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                }
    
    
    });
    
    
    
    }

    private void exit() {
      UIManager.put("OptionPane.yesButtonText", "Sim");
      UIManager.put("OptionPane.noButtonText", "Não");
      
       int op = JOptionPane.showConfirmDialog(null, "Você confirmar a saída?", "Atenção", JOptionPane.YES_NO_OPTION);
       
        if (op == 0){
        
         this.dispose();
    }
    }

    private void PesquisarView() {
      ViewPesquisar viewPesquisar = new ViewPesquisar();
      
      this.dispose();
      
      int op = 0;
      if (op == 0) {
      viewPesquisar.setVisible(true);
      viewPesquisar.setLocationRelativeTo(this);
      }
    }
}
    


    
    
    
    

